sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: content
        field:
          type: markdown
          localizable: true
      -
        handle: structures_field
        field:
          mode: select
          display: 'Structures Field'
          type: structures
          icon: structures
          listable: hidden
          instructions_position: above
          read_only: false
      -
        handle: array_field
        field:
          mode: dynamic
          keys:
            'null': null
          display: 'Array Field'
          type: array
          icon: array
          listable: hidden
          instructions_position: above
          read_only: false
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
title: Services
